database:
  dialect: mysql
  username: root
  password: root
  host: localhost
  port: 3306
  dbname: auth
  maxIdleConns: 10
  maxOpenConns: 100


redis:
  sentinel:
    masterName: mymaster
    password: ivargo_981
    addrs:
      - 192.168.0.205:26379
      - 192.168.0.206:26379
    db: 0
    poolSize: 200